#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"
LINK_FILE="LINK"
LINK_FILE_PATH="$DOKKU_ROOT/$APP/$LINK_FILE"

output=""
if [[ -f "$LINK_FILE_PATH" ]]; then
  while read line
  do
    IFS=':' read -ra LINK <<< $line
    NAME_ORIG=${LINK[0]}
    RESULT="$(exec docker ps | grep -i $NAME_ORIG)"
    RESULT_ARR=($RESULT)
    RESULT_ARR_LENGTH=${#RESULT_ARR[@]}
    LAST_POS=$((RESULT_ARR_LENGTH - 1))
    NAME=${RESULT_ARR[${LAST_POS}]}
    if (( ${#LINK[@]} > 1 )); then
      output="$output --link $NAME:${LINK[1]}"
    else
      output="$output --link $NAME:$NAME_ORIG"
    fi
  done < $LINK_FILE_PATH
fi
echo "$STDIN$output"
